apiVersion: "1.0.0"

app:
  name: "banner"
  env: "dev"
  version: "1.0"

postgres:
  host: "localhost"
  port: "5436"


logger:
  env: "dev" # "prod"
  level: "debug"
  outputs:
    - "stdout"
  error_outputs:
    - "stderr"
  encoding: "json"
  sentry_dsn: ""
  sentry_level: "error"

cache_refresher:
  iteration_interval: "10s"

postpone_deleter:
  iteration_interval: "10s"

cache:
  expiration: "900s"
  initial_size: 10000


tracer:
  enable: false
  exp_target: "jaeger-all-in-one:4317"

metrics:
  enable: false
  dsn: "<sentry_dsn_for_service>"

graceful_shutdown:
  delay: "5s"
  wait_timeout: "5s"
  callback_timeout: "2s"

http:
  host: "localhost"
  port: 8080
  read_timeout: "1s"
  write_timeout: "1s"

kafka_reader:
  brokers:
    - "kafka:9092"
  topic: "outbound"
  id_group: "banner-service"
  min_bytes: 32
  max_bytes: 2048

kafka_writer:
  broker: "kafka:9092"
  topic: "inbound"

